### ISSUE TITLE
Missing laxzip.cc (guessing)

### ISSUE THREAD

**Issue by Circuitsoft** [Laidout/laxkit#9]
`make: *** No rule to make target 'laxzip.o', needed by 'almostall'.  Stop.`

When I `touch`d laxzip.cc and laxzip.h to make empty files, there were errors elsewhere against ZipWriter and ZipReader. Checking out `HEAD^` then touching `lax/laxzip.cc` at least allowed the build to complete.

**Comment by tomlechner** [comment]
Whoops! I forgot to add those files. Should be fixed now, I just pushed changes to both Laidout and Laxkit repos.
